common/algorithm-terms.html, common/common.js, common/terms.html, common/typographical-conventions.html, index.html
Updated from the CG for the WG.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/1.html" title="Last updated on Jun 29, 2018, 5:51 PM GMT (f9bb62e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/1/0013b9e...f9bb62e.html" title="Last updated on Jun 29, 2018, 5:51 PM GMT (f9bb62e)">Diff</a>
=> Initial spec import

index.html, tests/toRdf-manifest.jsonld, tests/toRdf/wf01-in.jsonld, tests/toRdf/wf02-in.jsonld, tests/toRdf/wf03-in.jsonld, tests/toRdf/wf04-in.jsonld, tests/toRdf/wf04-out.nq, tests/toRdf/wf05-in.jsonld, tests/toRdf/wf06-in.jsonld, tests/toRdf/wf07-in.jsonld
Fixes #17.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/18.html" title="Last updated on Aug 11, 2018, 9:53 PM GMT (900b190)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/18/ecf9175...900b190.html" title="Last updated on Aug 11, 2018, 9:53 PM GMT (900b190)">Diff</a>
=> Update toRdf algorithm to require that all triples and graph names be well-formed.

tests/expand-manifest.jsonld
This reverts commit 2f4e97dd8ea3c4d706d40b17363546a5159d4589.
=> Revert "Fix expandContext path."

index.html
From json-ld/json-ld.org#662 and json-ld/json-ld.org#672.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/30.html" title="Last updated on Aug 27, 2018, 12:09 AM GMT (be83d13)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/30/2be6137...be83d13.html" title="Last updated on Aug 27, 2018, 12:09 AM GMT (be83d13)">Diff</a>
=> Api clarifications

index.html
=> Playground links to highlight algorithms.

.travis.yml, ECHIDNA
when pushed to "publications" branch.
=> Echidna configuration and Travis configuration for publication

index.html
@gkellogg do you want PRs for these kinds of tiny tweaks? Just didn't want to throw off your groove by committing to master. 😁
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/55.html" title="Last updated on Dec 13, 2018, 7:31 PM GMT (e207f5f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/55/268a0bb...e207f5f.html" title="Last updated on Dec 13, 2018, 7:31 PM GMT (e207f5f)">Diff</a>
=> Fix tiny typo

tests/fromRdf-manifest.jsonld, tests/fromRdf/0026-in.nq, tests/fromRdf/0026-out.jsonld
Adding test to cover a jsonld.js failure: https://github.com/digitalbazaar/jsonld.js/issues/294.
Is this output correct?
=> Test `<subject> <rdf:first> <rdf:nil>` triple.

common/extract-examples.rb, tests/compact/0007-context.jsonld, tests/compact/0007-out.jsonld, tests/compact/0009-context.jsonld, tests/compact/0009-out.jsonld, tests/context.jsonld, tests/expand/0011-in.jsonld, tests/expand/0012-in.jsonld, tests/flatten/0011-in.jsonld, tests/flatten/0012-in.jsonld, tests/mk_vocab.rb, tests/toRdf/0028-in.jsonld, tests/toRdf/0051-in.jsonld, tests/toRdf/0052-in.jsonld, tests/vocab.html, tests/vocab.jsonld, tests/vocab.ttl, tests/vocab_context.jsonld, tests/vocab_template.haml
=> Use "dcterms" in favor of "dc".

tests/compact-manifest.jsonld, tests/compact/c014-context.jsonld, tests/compact/c014-in.jsonld, tests/compact/c014-out.jsonld, tests/compact/c015-context.jsonld, tests/compact/c015-in.jsonld, tests/compact/c015-out.jsonld, tests/compact/c016-context.jsonld, tests/compact/c016-in.jsonld, tests/compact/c016-out.jsonld, tests/compact/c017-context.jsonld, tests/compact/c017-in.jsonld, tests/compact/c017-out.jsonld, tests/compact/c018-context.jsonld, tests/compact/c018-in.jsonld, tests/compact/c018-out.jsonld, tests/compact/c019-context.jsonld, tests/compact/c019-in.jsonld, tests/compact/c019-out.jsonld
=> Add more type-scoped compaction tests.

index.html
Fixes #99
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/102.html" title="Last updated on May 30, 2019, 10:51 PM UTC (fc72552)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/102/35c4feb...fc72552.html" title="Last updated on May 30, 2019, 10:51 PM UTC (fc72552)">Diff</a>
=> Issue 99 term context processing

README.md
Solves for https://github.com/w3c/json-ld-wg/issues/84
Let me know if this is copacetic and I'll do the same for framing and syntax.
=> Add feature freeze note

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/106.html" title="Last updated on Jun 12, 2019, 8:58 PM UTC (3b23b20)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/106/42772ce...3b23b20.html" title="Last updated on Jun 12, 2019, 8:58 PM UTC (3b23b20)">Diff</a>
=> Update example formatting.

tests/expand-manifest.jsonld
=> Only test expansion e005 with specVersion 1.1.

index.html
Fixes #100.
cc/@kasei.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/111.html" title="Last updated on Jun 17, 2019, 9:29 PM UTC (41d407b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/111/1466f97...41d407b.html" title="Last updated on Jun 17, 2019, 9:29 PM UTC (41d407b)">Diff</a>
=> Address @kasei's concerns on `@type` expansion.

tests/README.md
…  with specific reference to top-level manifest and individual algorithm manifests.
Fixes #113.
=> Update test README

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/124.html" title="Last updated on Jul 22, 2019, 10:25 PM UTC (a479531)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/124/61eb0a6...a479531.html" title="Last updated on Jul 22, 2019, 10:25 PM UTC (a479531)">Diff</a>
=> Fix latest WebIDL issues.

common/terms.html
This was initially supposed to be my review on #125, for which I was quite late (sorry about that).
=> Review terms pchampin

ack-script/ack_pattern.html, ack-script/acknowledgements.html, ack-script/separate_acks.json, index.html
Adds @dlongley as an editor.
@iherman: needs @dlongley's w3cid.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/156.html" title="Last updated on Sep 25, 2019, 4:21 PM UTC (5b2290a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/156/568fc9d...5b2290a.html" title="Last updated on Sep 25, 2019, 4:21 PM UTC (5b2290a)">Diff</a>
=> Update acknowledgements and editors.

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/182.html" title="Last updated on Oct 29, 2019, 9:56 PM UTC (46fac9d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/182/2f36a51...46fac9d.html" title="Last updated on Oct 29, 2019, 9:56 PM UTC (46fac9d)">Diff</a>
=> Addresses issue #176

common/common.js, common/terms.html
=> Update common files.

tests/toRdf-manifest.html, tests/toRdf-manifest.jsonld
=> Make toRdf/0118 1.0 only.

index.html
charac…ter, **if it is an IRI**.
Fixes #205.
cc/ @kasei.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/223.html" title="Last updated on Nov 25, 2019, 9:42 PM UTC (21ed62e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/223/b92159a...21ed62e.html" title="Last updated on Nov 25, 2019, 9:42 PM UTC (21ed62e)">Diff</a>
=> Qualify that a potential prefix term must end with a gen-delim

index.html
@kasei, please let us know if this satisfies issue #241.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/247.html" title="Last updated on Dec 18, 2019, 6:04 PM UTC (0255501)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/247/dd3dc99...0255501.html" title="Last updated on Dec 18, 2019, 6:04 PM UTC (0255501)">Diff</a>
=> Clarify 16.1 in Create Term Definition to satisfy #241.

index.html
@kasei, please indicate if this satisfies the issue you raised in #243.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/249.html" title="Last updated on Dec 18, 2019, 6:22 PM UTC (5832b50)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/249/129ee46...5832b50.html" title="Last updated on Dec 18, 2019, 6:22 PM UTC (5832b50)">Diff</a>
=> Remove duplicated text in the expansion algorithm.

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/268.html" title="Last updated on Dec 20, 2019, 11:46 PM UTC (cc65187)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/268/b6c3cce...cc65187.html" title="Last updated on Dec 20, 2019, 11:46 PM UTC (cc65187)">Diff</a>
=> add missing `@none` in step 13.4, addressing #259

index.html
Fixes #260.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/271.html" title="Last updated on Dec 20, 2019, 11:55 PM UTC (9409da2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/271/753d2e9...9409da2.html" title="Last updated on Dec 20, 2019, 11:55 PM UTC (9409da2)">Diff</a>
=> "the value" => "_value_".

index.html
For #264.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/274.html" title="Last updated on Dec 23, 2019, 8:48 PM UTC (576dd13)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/274/3e9626a...576dd13.html" title="Last updated on Dec 23, 2019, 8:48 PM UTC (576dd13)">Diff</a>
=> Improve wording in Expansion on type-maps.

index.html
For #292.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/293.html" title="Last updated on Dec 31, 2019, 6:36 PM UTC (7d4bfe8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/293/7db9078...7d4bfe8.html" title="Last updated on Dec 31, 2019, 6:36 PM UTC (7d4bfe8)">Diff</a>
=> Return early in step 15.3 of expansion algorithm.

index.html
For #290.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/291.html" title="Last updated on Dec 30, 2019, 9:18 PM UTC (350100d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/291/7db9078...350100d.html" title="Last updated on Dec 30, 2019, 9:18 PM UTC (350100d)">Diff</a>
=> Update expansion of property indexes.

index.html
For #309.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/319.html" title="Last updated on Jan 14, 2020, 11:05 PM UTC (4efbb8d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/319/5b0038b...4efbb8d.html" title="Last updated on Jan 14, 2020, 11:05 PM UTC (4efbb8d)">Diff</a>
=> Describe how entries are expanded in step 7 of the Expansion algorithm.

index.html
For #310.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/320.html" title="Last updated on Jan 14, 2020, 11:27 PM UTC (a37df36)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/320/5b0038b...a37df36.html" title="Last updated on Jan 14, 2020, 11:27 PM UTC (a37df36)">Diff</a>
=> Add text in list expansion to ensure that the result is an array.

index.html
Fixes #321.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/326.html" title="Last updated on Jan 17, 2020, 6:47 PM UTC (1cc03e5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/326/61aaa43...1cc03e5.html" title="Last updated on Jan 17, 2020, 6:47 PM UTC (1cc03e5)">Diff</a>
=> Clarify sub-steps of step 4 of the Value Compaction algorithm.

index.html
address #312
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/317.html" title="Last updated on Jan 24, 2020, 11:15 AM UTC (60f2c2f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/317/89e5fbb...60f2c2f.html" title="Last updated on Jan 24, 2020, 11:15 AM UTC (60f2c2f)">Diff</a>
=> clarified handling of big integers as doubles

tests/expand-manifest.html, tests/expand-manifest.jsonld, tests/expand/c033-in.jsonld, tests/toRdf-manifest.html, tests/toRdf-manifest.jsonld, tests/toRdf/c033-in.jsonld
Additional test related to:
- https://github.com/w3c/json-ld-api/issues/331
- https://github.com/w3c/json-ld-api/pull/340
=> Add another unused scoped context error test.

index.html
Fixes #357.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/361.html" title="Last updated on Jan 30, 2020, 11:28 PM UTC (2d21915)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/361/2f57a54...2d21915.html" title="Last updated on Jan 30, 2020, 11:28 PM UTC (2d21915)">Diff</a>
=> Clarify when value is a map in IRI Compaction.

.travis.yml, index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/376.html" title="Last updated on Feb 16, 2020, 12:13 AM UTC (00712a3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/376/dcd4869...00712a3.html" title="Last updated on Feb 16, 2020, 12:13 AM UTC (00712a3)">Diff</a>
=> Changes since cr

tests/expand-manifest.html, tests/expand-manifest.jsonld, tests/expand/e016-in.jsonld
This relates to changes to pr38 and pr39.
=> Remove expand/e016, which is obsolete.

tests/expand-manifest.html, tests/expand-manifest.jsonld, tests/expand/er53-in.jsonld, tests/toRdf-manifest.html, tests/toRdf-manifest.jsonld, tests/toRdf/er53-in.jsonld
=> Add tests for invalid prefix values, Closes #432

reports/perl-jsonld-earl.ttl
Fixed the failures that were submitted yesterday (mostly fixes to the test harness).
=> Updated perl JSONLD implementation report.

reports/template.haml
"failing" here means: "passed by less than 2 implementations"
=> CSS trick to visually mark failing tests

index.html, tests/README.md, tests/compact-manifest.html, tests/expand-manifest.html, tests/flatten-manifest.html, tests/html-manifest.html, tests/manifest.html, tests/remote-doc-manifest.html, tests/template.haml
* Add test information for **PositiveSyntaxTest*. Fixes #449.
* Updated step 5.13 of the Context Processing algorithm to pass override protected to the Create Term Definition algorithm. Fixes #450.
* Updated step 5.13 of the Context Processing algorithm to not pass validate scoped context to the Create Term Definition algorithm. Fixes #451.
* Move step 5.2.2 of the Context Processing algorithm to run before the subsequent step for checking remote contexts. Fixes #452.
* Minor improvement to wording in Create Term Definition when validating IRIs. Fixes #453.
* Fix optional argument count to the Serialize RDF as JSON-LD Algorithm from five to four, and update default values, noting that `rdfDirection` is not actually a flag. Fixes #460.
* Update substeps of 6.1.6 in the Serialize RDF as …
=> Minor update

reports/rust-sophia-earl.ttl
there will be a (partial) Rust implementation after all ;-)
=> implementation report for Sophia (fromRdf only)

reports/pyld-earl.ttl
=> Update PyLD report for 2.0.1.

tests/expand-manifest.html, tests/expand-manifest.jsonld, tests/toRdf-manifest.html, tests/toRdf-manifest.jsonld
=> Update expand and toRdf tests ter53 to be for specVersion json-ld-1.1.

errata/index.html
This should be merged when the document is published.
=> Finalize date of errata

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/520.html" title="Last updated on Jan 5, 2021, 3:50 PM UTC (d8255b1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/520/7975314...d8255b1.html" title="Last updated on Jan 5, 2021, 3:50 PM UTC (d8255b1)">Diff</a>
=> address issue #519

Gemfile.lock, index.html, tests/compact-manifest.html, tests/compact-manifest.jsonld, tests/compact/0111-context.jsonld, tests/compact/0111-in.jsonld, tests/compact/0111-out.jsonld
Addresses #524
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/525.html" title="Last updated on Feb 26, 2021, 7:30 AM UTC (6e86a10)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/525/ee53b08...6e86a10.html" title="Last updated on Feb 26, 2021, 7:30 AM UTC (6e86a10)">Diff</a>
=> Clarification and test-case about compacting keyword-like relative IRIs

tests/expand-manifest.jsonld
=> Normalize indents.

tests/compact-manifest.jsonld
=> Remove duplicate keys in compact 0108 JSON-LD manifest.

.gitignore, index.html
Fixes #605.
***
<a href="https://pr-preview.s3.amazonaws.com/iolanta-tech/json-ld-api/pull/608.html" title="Last updated on Jan 27, 2025, 5:57 PM UTC (def68a1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/608/a24a4b3...iolanta-tech:def68a1.html" title="Last updated on Jan 27, 2025, 5:57 PM UTC (def68a1)">Diff</a>
=> Resolve the questions about "JSON Serialization" term
