w3c/json-ld-api

- index.html
as considered in https://github.com/json-ld/json-ld.org/issues/357#issuecomment-55641174.
Fixes #13.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/15.html" title="Last updated on Aug 2, 2018, 12:24 AM GMT (2a38c88)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/15/5457f25...2a38c88.html" title="Last updated on Aug 2, 2018, 12:24 AM GMT (2a38c88)">Diff</a>
> Update fromRdf algorithm to consider list nodes that are in multiple graphs

- index.html
algorithm, as _node_ referred to two different things and was inaccurate when used for adding property values to the active subject node.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/12.html" title="Last updated on Jul 31, 2018, 5:40 PM GMT (5e4c868)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/12/5457f25...5e4c868.html" title="Last updated on Jul 31, 2018, 5:40 PM GMT (5e4c868)">Diff</a>
> Fix double use of _node_ variable in Node Map Generation 

- index.html
Fixes #10.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/19.html" title="Last updated on Aug 15, 2018, 12:05 AM GMT (35bf4a7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/19/a335fba...35bf4a7.html" title="Last updated on Aug 15, 2018, 12:05 AM GMT (35bf4a7)">Diff</a>
> Add missing _node map_ argument for recursive call.

- common/common.js
- common/terms.html
- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/31.html" title="Last updated on Aug 28, 2018, 4:45 PM GMT (5277a28)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/31/760b32f...5277a28.html" title="Last updated on Aug 28, 2018, 4:45 PM GMT (5277a28)">Diff</a>
> Improve terminology on dictionaries, dictionary members and JSON objects to be more consistent.

- common/terms.html
- index.html
Defines new interfaces for RdfDataset, RdfGraph, RdfTriple, and RdfLiteral.
Fixes #27.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/35.html" title="Last updated on Sep 13, 2018, 6:33 PM GMT (12c7958)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/35/113d2f8...12c7958.html" title="Last updated on Sep 13, 2018, 6:33 PM GMT (12c7958)">Diff</a>
> WebIDL for `fromRdf` and `toRdf` algorithms

- index.html
- tests/compact-manifest.jsonld
- tests/compact/0104-context.jsonld
- tests/compact/0104-in.jsonld
- tests/compact/0104-out.jsonld
- tests/compact/0105-context.jsonld
- tests/compact/0105-in.jsonld
- tests/compact/0105-out.jsonld
- tests/compact/0106-context.jsonld
- tests/compact/0106-in.jsonld
- tests/compact/0106-out.jsonld
- tests/expand-manifest.jsonld
- tests/expand/e042-in.jsonld
or an alias in 1.1. Remains an error to redefine `@type` in 1.0.
For w3c/json-ld-syntax#34.
> Algorithm updates and tests to allow `@container: @set` on @type

- index.html
- tests/expand-manifest.jsonld
- tests/expand/0109-in.jsonld
- tests/expand/0109-out.jsonld
but continue processing.
Fixes w3c/json-ld-syntax#66.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/42.html" title="Last updated on Oct 4, 2018, 8:05 PM GMT (2eb2a7f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/42/3ce32cb...2eb2a7f.html" title="Last updated on Oct 4, 2018, 8:05 PM GMT (2eb2a7f)">Diff</a>
> Update IRI Expansion to not return values including a : that are not absolute IRIs

- tests/expand-manifest.jsonld
The expand fixtures otherwise appear clean, but haven't tested the other test categories yet. This sort of thing currently fails in certain JSON parsers (serde in my case).
> Fix duplicate name in `tests/expand-manifest.jsonld`

- common/algorithm-terms.html
- common/terms.html
- index.html
* Make definition identifiers singular, and use automatic term pluralization.
* Update previous published version.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/46.html" title="Last updated on Oct 12, 2018, 9:24 PM GMT (48ee88b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/46/4c006ba...48ee88b.html" title="Last updated on Oct 12, 2018, 9:24 PM GMT (48ee88b)">Diff</a>
> Dfn cleanup

- index.html
as _active property_ will never be `@list`, but it's _container mapping_ may include `@list`.
Fixes #47.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/48.html" title="Last updated on Oct 15, 2018, 6:24 PM GMT (08d5708)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/48/2e8b486...08d5708.html" title="Last updated on Oct 15, 2018, 6:24 PM GMT (08d5708)">Diff</a>
> Simplify check when expanding array

- common/algorithm-terms.html
- common/terms.html
- common/typographical-conventions.html
- index.html
… and generalized RDF datasets.
Fixes w3c/syntax#37.
> Mark blank node property labels as obsolete

- common/extract-examples.rb
- index.html
- tests/expand-manifest.jsonld
- tests/expand/h018-in.html
- tests/expand/h018-out.jsonld
- tests/expand/h019-in.html
- tests/expand/h019-out.jsonld
- tests/expand/h020-in.html
- tests/expand/h020-out.jsonld
- tests/expand/h021-in.html
- tests/expand/h021-out.jsonld
- tests/expand/h022-in.html
- tests/expand/h022-out.jsonld
For w3c/json-ld-syntax#23.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/51.html" title="Last updated on Nov 29, 2018, 12:25 AM GMT (b969d20)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/51/7f99a50...b969d20.html" title="Last updated on Nov 29, 2018, 12:25 AM GMT (b969d20)">Diff</a>
> Text and tests for using HTML base for embedded JSON-LD.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/52.html" title="Last updated on Dec 6, 2018, 11:44 PM GMT (2d20859)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/52/53fcabc...2d20859.html" title="Last updated on Dec 6, 2018, 11:44 PM GMT (2d20859)">Diff</a>
> Clarify iri compaction

- Gemfile.lock
- common/extract-examples.rb
- index.html
- tests/expand/h010-out.jsonld
For w3c/json-ld-syntax#100.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/54.html" title="Last updated on Dec 8, 2018, 9:30 PM GMT (f9236d8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/54/e2ba014...f9236d8.html" title="Last updated on Dec 8, 2018, 9:30 PM GMT (f9236d8)">Diff</a>
> Don't do HTML html decoding, and update expand/h010 to reflect this.

- tests/README.md
- tests/context.jsonld
- tests/mk_vocab.rb
- tests/vocab.html
- tests/vocab.jsonld
- tests/vocab.ttl
- tests/vocab_context.jsonld
- tests/vocab_template.haml
This allows for changing the vocabulary for WG purposes rather than depending on the CG version.
Change is localized to the `@context` used in the main test manifest; no change for test runners using the JSON representation of the manifests.
> Use test-vocabulary in this repo, rather than json-ld.org.

- .travis.yml
- Gemfile.lock
- common/terms.html
- index.html
- tests/compact-manifest.jsonld
- tests/compact/0107-context.jsonld
- tests/compact/0107-in.jsonld
- tests/compact/0107-out.jsonld
- tests/expand-manifest.jsonld
- tests/expand/0110-in.jsonld
- tests/expand/0110-out.jsonld
- tests/expand/0111-in.jsonld
- tests/expand/0111-out.jsonld
- tests/expand/0112-in.jsonld
- tests/expand/0112-out.jsonld
- tests/flatten-manifest.jsonld
- tests/toRdf-manifest.jsonld
This update spec and tests to allow any relative IRI as the value of `@vocab`, not just the empty string.
For w3c/json-ld-syntax#72.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/58.html" title="Last updated on Jan 12, 2019, 10:23 PM UTC (460c0a9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/58/22aed10...460c0a9.html" title="Last updated on Jan 12, 2019, 10:23 PM UTC (460c0a9)">Diff</a>
> Relative vocab

- Gemfile.lock
- Rakefile
- common/terms.html
- index.html
- tests/expand-manifest.jsonld
Note, as the text says that the depth of inclusion is processor defined, there are no new tests for this, and the old expansion tests that looked for recursive context inclusion are now 1.0 only.
For #14.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/62.html" title="Last updated on Feb 16, 2019, 8:49 PM UTC (0d72f9d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/62/a1e1e30...0d72f9d.html" title="Last updated on Feb 16, 2019, 8:49 PM UTC (0d72f9d)">Diff</a>
> Issue 14 circular imports

- index.html
- tests/compact-manifest.jsonld
- tests/compact/tn01-context.jsonld
- tests/compact/tn01-in.jsonld
- tests/compact/tn01-out.jsonld
- tests/compact/tn02-context.jsonld
- tests/compact/tn02-in.jsonld
- tests/compact/tn02-out.jsonld
- tests/compact/tn03-context.jsonld
- tests/compact/tn03-in.jsonld
- tests/compact/tn03-out.jsonld
- tests/expand-manifest.jsonld
- tests/expand/tn01-in.jsonld
- tests/expand/tn02-in.jsonld
- tests/expand/tn02-out.jsonld
* Updates value expansion and value compaction, inverse contexts, and term selection.
* Causes all value objects which are not compacted away to have their keywords and value of `@type` compacted.
For #33.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/63.html" title="Last updated on Feb 18, 2019, 8:07 PM UTC (6a2dd38)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/63/cad346a...6a2dd38.html" title="Last updated on Feb 18, 2019, 8:07 PM UTC (6a2dd38)">Diff</a>
> Add support for `@type: @none` in term definitions.

- tests/fromRdf-manifest.jsonld
- tests/fromRdf/0024-in.nq
- tests/fromRdf/0024-out.jsonld
- tests/fromRdf/0025-in.nq
- tests/fromRdf/0025-out.jsonld
- Add tests for triples with same the subject, property and value but
different languages or datatypes. Helps to expose possible N-Quads
parsing bugs.
- Used to check and fix https://github.com/digitalbazaar/jsonld.js/issues/293.
> Add literal value tests.

- tests/remote-doc-manifest.jsonld
Looks like this context should point at a valid URL.
> Fix remote-doc-manifest context.

- common/jsonld.js
- common/terms.html
- tests/compact-manifest.jsonld
- tests/compact/0108-context.jsonld
- tests/compact/0108-in.jsonld
- tests/compact/0108-out.jsonld
- tests/expand-manifest.jsonld
- tests/expand/0113-in.jsonld
- tests/expand/0113-out.jsonld
- tests/flatten-manifest.jsonld
- tests/flatten/0049-in.jsonld
- tests/flatten/0049-out.jsonld
These tests are particular to a bug in the jsonld.js implementation.  They could stay in the test suite of that lib, but I figured no harm in adding them to the main test suite to potentially catch issues in future javascript implementations.
> Add JavaScript Object property name tests.

- index.html
- tests/toRdf-manifest.jsonld
- tests/toRdf/rt01-in.jsonld
- tests/toRdf/rt01-out.nq
to consider non-fractional numbers >= 0e21 and add test.
> Update round-tripping of numbers

- index.html
- tests/compact/ep09-context.jsonld
- tests/compact/p007-context.jsonld
- tests/compact/p007-in.jsonld
- tests/compact/p007-out.jsonld
- tests/expand-manifest.jsonld
- tests/expand/0025-in.jsonld
- tests/expand/0025-out.jsonld
- tests/expand/e043-in.jsonld
- tests/expand/e044-in.jsonld
- tests/expand/e045-in.jsonld
- tests/flatten-manifest.jsonld
- tests/flatten/0025-in.jsonld
- tests/flatten/0025-out.jsonld
- tests/toRdf-manifest.jsonld
- tests/toRdf/0065-in.jsonld
- tests/toRdf/0065-out.nq
which do not expand in a natural way.
For w3c/json-ld-syntax#155
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/82.html" title="Last updated on Apr 24, 2019, 5:45 PM UTC (cffd00e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/82/ef43954...cffd00e.html" title="Last updated on Apr 24, 2019, 5:45 PM UTC (cffd00e)">Diff</a>
> Add checks for terms including a colon

- index.html
For #66.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/84.html" title="Last updated on May 3, 2019, 5:22 PM UTC (a26150e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/84/8cf5a5a...a26150e.html" title="Last updated on May 3, 2019, 5:22 PM UTC (a26150e)">Diff</a>
> Reference definitions for processor levels to syntax document.

- index.html
Should be of type `RemoteDocument`, not `USVString`.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/86.html" title="Last updated on May 3, 2019, 5:44 PM UTC (b610779)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/86/8cf5a5a...b610779.html" title="Last updated on May 3, 2019, 5:44 PM UTC (b610779)">Diff</a>
> The LoadDocumentCallback returns a broken Promise

- index.html
It had some leftover steps from the toRdf API description, which could simply be removed.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/88.html" title="Last updated on May 4, 2019, 8:59 PM UTC (cd8cd25)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/88/c628bdd...cd8cd25.html" title="Last updated on May 4, 2019, 8:59 PM UTC (cd8cd25)">Diff</a>
> Fix broken fromRdf API description.

- index.html
to include most HTML-specific and profile-specific processing, and use in *expand* and *Context Processing*.
For #85.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/87.html" title="Last updated on May 6, 2019, 9:20 PM UTC (27f650f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/87/cbf6f4f...27f650f.html" title="Last updated on May 6, 2019, 9:20 PM UTC (27f650f)">Diff</a>
> Rewrite LoadDocumentCallback

- index.html
I added these class for the sake of homogeneity (and also because I'm not sure how "normativeness" propagates through subsections...
I set "Terminology" as normative because it is so in the other specs. The "Example conventions" looked informative to me, but I prefer to check.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/95.html" title="Last updated on May 24, 2019, 4:31 PM UTC (05a64b9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/95/c71d460...05a64b9.html" title="Last updated on May 24, 2019, 4:31 PM UTC (05a64b9)">Diff</a>
> added missing normative/informative class in intro

- tests/README.md
This updates the mailing list mentioned in the tests/README.md under in the contributing section.
It's what I found looking for `json-ld-wg@w3.org`, linked from https://www.w3.org/2018/json-ld-wg/.
> Update public mailing list

- index.html
Fixes #91.
cc/ @kasei
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/101.html" title="Last updated on May 30, 2019, 12:10 AM UTC (3e9a886)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/101/1a31a17...3e9a886.html" title="Last updated on May 30, 2019, 12:10 AM UTC (3e9a886)">Diff</a>
> Improve wording in Expansion Algorithm.

- tests/toRdf-manifest.jsonld
- tests/toRdf/0130-in.jsonld
- tests/toRdf/0130-out.nq
- tests/toRdf/0131-in.jsonld
- tests/toRdf/0131-out.nq
- tests/toRdf/0132-in.jsonld
- tests/toRdf/0132-out.nq
This came up in an issue with jsonld-java:
https://github.com/jsonld-java/jsonld-java/issues/232
See second bullet point in:
https://tools.ietf.org/html/rfc3986#section-5.2.3
> Add toRdf tests for merging rootless base paths

- index.html
- tests/expand-manifest.jsonld
- tests/expand/pr23-in.jsonld
- tests/expand/pr23-out.jsonld
- tests/expand/pr24-in.jsonld
- tests/expand/pr24-out.jsonld
- tests/expand/pr25-in.jsonld
- tests/expand/pr25-out.jsonld
- tests/expand/pr26-in.jsonld
- tests/expand/pr27-in.jsonld
- tests/expand/pr27-out.jsonld
- tests/expand/pr28-in.jsonld
A few of these tests look a bit crazy.  Sorry. ;-)  Suggested improvements would be welcome.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/92.html" title="Last updated on Jun 12, 2019, 5:21 PM UTC (71612ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/92/849e153...71612ae.html" title="Last updated on Jun 12, 2019, 5:21 PM UTC (71612ae)">Diff</a>
> Add protected term redefinition tests.

- index.html
- tests/expand-manifest.jsonld
- tests/expand/0014-in.jsonld
- tests/expand/0048-in.jsonld
- tests/expand/0048-out.jsonld
- tests/expand/pr29-in.jsonld
- tests/expand/pr29-out.jsonld
- tests/flatten-manifest.jsonld
- tests/toRdf-manifest.jsonld
- tests/toRdf/0088-in.jsonld
- tests/toRdf/0088-out.nq
Update tests and Expand IRI to not consider terms where the _prefix flag_ is false when considering Compact IRIs.
Fixes w3c/json-ld-wg#90 and fixes w3c/json-ld-wg#87.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/109.html" title="Last updated on Jun 15, 2019, 1:39 PM UTC (bb9c9b4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/109/1466f97...bb9c9b4.html" title="Last updated on Jun 15, 2019, 1:39 PM UTC (bb9c9b4)">Diff</a>
> Compact IRI expansion with prefix flag false

- index.html
- tests/compact-manifest.jsonld
- tests/compact/e002-context.jsonld
- tests/compact/e002-in.jsonld
…where the scheme matches a term in the active context.
Fixes #104.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/110.html" title="Last updated on Jun 17, 2019, 8:29 PM UTC (d2302d9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/110/1466f97...d2302d9.html" title="Last updated on Jun 17, 2019, 8:29 PM UTC (d2302d9)">Diff</a>
> Detect an attempt to compact an IRI which results in an absolute IRI

- common/algorithm-terms.html
- common/terms.html
- index.html
For w3c/syntax#199.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/116.html" title="Last updated on Jul 10, 2019, 6:37 PM UTC (ecc116d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/116/a0a0893...ecc116d.html" title="Last updated on Jul 10, 2019, 6:37 PM UTC (ecc116d)">Diff</a>
> Update terms to use INFRA in place of WebIDL where reasonable.

- common/terms.html
- index.html
Use type-scoped and property-scoped terms, and take advantage of "context definition" as the shape of a map used as a context.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/117.html" title="Last updated on Jul 12, 2019, 11:00 PM UTC (c0b37bd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/117/816151c...c0b37bd.html" title="Last updated on Jul 12, 2019, 11:00 PM UTC (c0b37bd)">Diff</a>
> Context definitions

- common/algorithm-terms.html
- index.html
@marcoscaceres, this addresses the issues you raised in https://github.com/w3c/json-ld-syntax/pull/198, although in this spec, first.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/118.html" title="Last updated on Jul 14, 2019, 5:17 PM UTC (382530d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/118/c10240a...382530d.html" title="Last updated on Jul 14, 2019, 5:17 PM UTC (382530d)">Diff</a>
> Don't define _promise_ but use {{Promise}} reference.

- common/algorithm-terms.html
- common/terms.html
- index.html
for w3c/json-ld-syntax#185.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/125.html" title="Last updated on Jul 22, 2019, 5:13 PM UTC (780f00b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/125/91311ff...780f00b.html" title="Last updated on Jul 22, 2019, 5:13 PM UTC (780f00b)">Diff</a>
> Term updates

- index.html
- tests/compact-manifest.jsonld
- tests/compact/m020-context.jsonld
- tests/compact/m020-in.jsonld
- tests/compact/m020-out.jsonld
- tests/compact/m021-context.jsonld
- tests/compact/m021-in.jsonld
- tests/compact/m021-out.jsonld
- tests/compact/m022-context.jsonld
- tests/compact/m022-in.jsonld
- tests/compact/m022-out.jsonld
- tests/compact/s001-out.jsonld
- tests/compact/s002-out.jsonld
- tests/expand-manifest.jsonld
- tests/expand/m017-in.jsonld
- tests/expand/m017-out.jsonld
- tests/expand/m018-in.jsonld
- tests/expand/m018-out.jsonld
- tests/expand/m019-in.jsonld
- tests/expand/m019-out.jsonld
- tests/expand/m020-in.jsonld
- tests/toRdf-manifest.jsonld
- tests/toRdf/m017-in.jsonld
- tests/toRdf/m017-out.nq
- tests/toRdf/m018-in.jsonld
- tests/toRdf/m018-out.nq
- tests/toRdf/m019-in.jsonld
- tests/toRdf/m019-out.nq
- tests/toRdf/m020-in.jsonld
Also, fix compaction of type maps to have string values instead of node references.
Fixes #121.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/123.html" title="Last updated on Jul 21, 2019, 9:55 PM UTC (e15feb1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/123/91311ff...e15feb1.html" title="Last updated on Jul 21, 2019, 9:55 PM UTC (e15feb1)">Diff</a>
> `@container: @type` implies and requires that `@type` not be a literal.

- common/terms.html
- index.html
- tests/expand-manifest.jsonld
- tests/expand/0114-in.jsonld
- tests/expand/0114-out.jsonld
- tests/expand/n008-in.jsonld
- tests/expand/n008-out.jsonld
- tests/toRdf-manifest.jsonld
- tests/toRdf/e114-in.jsonld
- tests/toRdf/e114-out.nq
- tests/toRdf/n008-in.jsonld
- tests/toRdf/n008-out.nq
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/127.html" title="Last updated on Jul 26, 2019, 5:57 PM UTC (7165fb2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/127/74781a0...7165fb2.html" title="Last updated on Jul 26, 2019, 5:57 PM UTC (7165fb2)">Diff</a>
> Allow `@type` to be duplicated, either through aliasing, or nesting.

- index.html
In a number of places, the `inverse parameter` is missing
from calls to the `IRI Compaction algorithm`.
I have been assuming that the `inverse paramter`
from the calling algorithm was always to be passed as is.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/131.html" title="Last updated on Aug 7, 2019, 6:32 PM UTC (317e5c6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/131/83a39d2...317e5c6.html" title="Last updated on Aug 7, 2019, 6:32 PM UTC (317e5c6)">Diff</a>
> add missing parameter

- index.html
- tests/remote-doc-manifest.jsonld
- tests/remote-doc/la01-alternate.jsonld
- tests/remote-doc/la01-in.html
- tests/remote-doc/la01-out.jsonld
- tests/remote-doc/la02-alternate.jsonld
- tests/remote-doc/la02-in.jsonld
- tests/remote-doc/la02-out.jsonld
- tests/remote-doc/la03-alternate.json
- tests/remote-doc/la03-in.json
- tests/remote-doc/la03-out.jsonld
- tests/remote-doc/la04-alternate.jsonld
- tests/remote-doc/la04-in.json
- tests/remote-doc/la04-out.jsonld
- tests/remote-doc/la05-alternate.jsonld
- tests/remote-doc/la05-in.html
- tests/remote-doc/la05-out.jsonld
… with type `application/ld+json` to be used as a redirect if the retrieved document is not JSON.
For w3c/json-ld-syntax#204.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/133.html" title="Last updated on Aug 14, 2019, 4:25 PM UTC (caecf69)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/133/a8094d9...caecf69.html" title="Last updated on Aug 14, 2019, 4:25 PM UTC (caecf69)">Diff</a>
> Add support for the `alternate` link relation

- index.html
- tests/remote-doc-manifest.jsonld
- tests/remote-doc/la05-out.jsonld
not that of the original URL.
Fixes #139
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/142.html" title="Last updated on Aug 27, 2019, 6:01 PM UTC (54ab6e9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/142/ca800b3...54ab6e9.html" title="Last updated on Aug 27, 2019, 6:01 PM UTC (54ab6e9)">Diff</a>
> Base URL for rel=alternate is the alternate URL

- common/algorithm-terms.html
- index.html
- tests/compact-manifest.jsonld
- tests/compact/0109-context.jsonld
- tests/compact/0109-in.jsonld
- tests/compact/0109-out.jsonld
- tests/compact/0110-context.jsonld
- tests/compact/0110-in.jsonld
- tests/compact/0110-out.jsonld
... using `@included`, to make sure they are all contained in a single graph.
Fixes #143.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/146.html" title="Last updated on Sep 2, 2019, 8:44 PM UTC (b3cf1f1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/146/717ea94...b3cf1f1.html" title="Last updated on Sep 2, 2019, 8:44 PM UTC (b3cf1f1)">Diff</a>
> Wrap multiple object values of a term which is a graph container

- index.html
@gkellogg, need to do this in two rounds... this will fix the ReSpec errors for now, but once picked up by Shepherd (in ~12-24hours), we will need to do one small fix: convert `{{jsonldoptions/` to `{{JsonLdOptions/` then everything should be good.
***
<a href="https://pr-preview.s3.amazonaws.com/marcoscaceres/json-ld-api/pull/148.html" title="Last updated on Sep 7, 2019, 12:34 AM UTC (fca180a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/148/5f73c3d...marcoscaceres:fca180a.html" title="Last updated on Sep 7, 2019, 12:34 AM UTC (fca180a)">Diff</a>
> Fix ReSpec errors

- index.html
- tests/fromRdf-manifest.jsonld
- tests/fromRdf/js08-in.nq
- tests/fromRdf/js09-in.nq
Fixes #149
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/150.html" title="Last updated on Sep 11, 2019, 7:40 PM UTC (53b941f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/150/dd0311b...53b941f.html" title="Last updated on Sep 11, 2019, 7:40 PM UTC (53b941f)">Diff</a>
> Add invalid JSON literal error and tests.

- index.html
- tests/compact-manifest.html
- tests/compact-manifest.jsonld
- tests/compact/js10-context.jsonld
- tests/compact/js10-in.jsonld
- tests/compact/js10-out.jsonld
- tests/compact/js11-context.jsonld
- tests/compact/js11-in.jsonld
- tests/compact/js11-out.jsonld
- tests/expand-manifest.html
- tests/expand-manifest.jsonld
- tests/expand/js11-in.jsonld
- tests/expand/js11-out.jsonld
- tests/expand/js12-in.jsonld
- tests/expand/js12-out.jsonld
- tests/flatten-manifest.html
- tests/fromRdf-manifest.html
- tests/fromRdf-manifest.jsonld
- tests/fromRdf/js10-in.nq
- tests/fromRdf/js10-out.jsonld
- tests/fromRdf/js11-in.nq
- tests/fromRdf/js11-out.jsonld
- tests/html-manifest.html
- tests/remote-doc-manifest.html
- tests/toRdf-manifest.html
- tests/toRdf-manifest.jsonld
- tests/toRdf/js14-in.jsonld
- tests/toRdf/js14-out.nq
- tests/toRdf/js15-in.jsonld
- tests/toRdf/js15-out.nq
Supplemental to #149.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/155.html" title="Last updated on Sep 23, 2019, 8:05 PM UTC (d78f6b0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/155/ea646cb...d78f6b0.html" title="Last updated on Sep 23, 2019, 8:05 PM UTC (d78f6b0)">Diff</a>
> Add minor spec update and tests for JSON literal string and null values.

- index.html
- tests/expand-manifest.html
- tests/expand-manifest.jsonld
- tests/expand/pr30-in.jsonld
- tests/expand/pr30-out.jsonld
- tests/expand/pr31-in.jsonld
- tests/expand/pr32-in.jsonld
- tests/toRdf-manifest.html
- tests/toRdf-manifest.jsonld
- tests/toRdf/pr30-in.jsonld
- tests/toRdf/pr30-out.nq
- tests/toRdf/pr31-in.jsonld
- tests/toRdf/pr32-in.jsonld
For w3c/json-ld-syntax#246.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/158.html" title="Last updated on Sep 30, 2019, 6:42 PM UTC (3a748f4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/158/565f239...3a748f4.html" title="Last updated on Sep 30, 2019, 6:42 PM UTC (3a748f4)">Diff</a>
> Add tests to check for keyword redefinition allowing `@protected`.

- index.html
This respec dfn support seems difficult to use.  Looking for comments if this patch is doing the right thing.
- The "iterable" properties didn't have a automatic `<code>` around them when using the dfn stuff.  Not sure why?  Other properties worked.  Added that by hand and made the RdfGraph version linkable.
- That `graphName` word looked out of place, so tried to link it back to the func arg, but couldn't figure out how other than with a hand written href.  That is probably wrong.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/163.html" title="Last updated on Oct 10, 2019, 9:55 PM UTC (f35b9e6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/163/9e19e9f...f35b9e6.html" title="Last updated on Oct 10, 2019, 9:55 PM UTC (f35b9e6)">Diff</a>
> Fix IDL markup issues.

- common/terms.html
- index.html
- tests/README.md
- tests/compact-manifest.html
- tests/compact-manifest.jsonld
- tests/compact/la01-context.jsonld
- tests/compact/la01-in.jsonld
- tests/compact/la01-out.jsonld
- tests/expand-manifest.html
- tests/flatten-manifest.html
- tests/fromRdf-manifest.html
- tests/html-manifest.html
- tests/manifest.html
- tests/remote-doc-manifest.html
- tests/template.haml
- tests/toRdf-manifest.html
* Remove requirement to normalize language tags to lower case, but note testing considerations.
* Notes about normalizing language tags, issuing warnings when not well-formed, and not considering case when using for term selection.
* Add a test for term selection where case of language does not match.
For #167.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/168.html" title="Last updated on Oct 14, 2019, 9:18 PM UTC (1c62284)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/168/5e314e9...1c62284.html" title="Last updated on Oct 14, 2019, 9:18 PM UTC (1c62284)">Diff</a>
> Language tags

- tests/compact-manifest.html
- tests/expand-manifest.html
- tests/flatten-manifest.html
- tests/fromRdf-manifest.html
- tests/html-manifest.html
- tests/manifest.html
- tests/remote-doc-manifest.html
- tests/template.haml
- tests/toRdf-manifest.html
The links e.g. to manifest.jsonld were giving a 404, pointing to a file `json_file`,
It looks like the template was missing the necessary details to expand the variable json_file.
You can currently observe the behavior by clicking the `manifest.jsonld` links at the following.
* [json-ld-api-tests](https://w3c.github.io/json-ld-api/tests/)
* [json-framing-ld-tests](https://w3c.github.io/json-ld-framing/tests/)
> Fix expansion of link template variable json_file, regenerate html.

- index.html
containing an _IRI_ as the value of `@type` when framing.
For w3c/json-ld-framing#74.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/174.html" title="Last updated on Oct 21, 2019, 5:16 PM UTC (f6c7fb2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/174/2abfba2...f6c7fb2.html" title="Last updated on Oct 21, 2019, 5:16 PM UTC (f6c7fb2)">Diff</a>
> Add wording to allow a default object

- index.html
Separate creating map context from rolling back term-scoped context when expanding container maps for `@id` and `@type`.
Fixes #159.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/173.html" title="Last updated on Oct 18, 2019, 10:07 PM UTC (d6f2e0d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/173/cebd4fc...d6f2e0d.html" title="Last updated on Oct 18, 2019, 10:07 PM UTC (d6f2e0d)">Diff</a>
> Expand contexts when processing keys in id-map.

- index.html
in expansion algorithm.
Fixes #178.
cc/ @kasei
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/179.html" title="Last updated on Oct 28, 2019, 9:57 PM UTC (cb8ba95)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/179/629ec61...cb8ba95.html" title="Last updated on Oct 28, 2019, 9:57 PM UTC (cb8ba95)">Diff</a>
> Remove incomplete and redundant step for `@type` and `@included`

- index.html
for _document relative_.
Fixes #180.
cc/ @kasie
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/187.html" title="Last updated on Oct 30, 2019, 11:33 PM UTC (43b17f9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/187/6b43cf6...43b17f9.html" title="Last updated on Oct 30, 2019, 11:33 PM UTC (43b17f9)">Diff</a>
> Clarify that IRI expansion uses _base IRI_ from _active context_

- index.html
only apply when _result_ is a map.
Also,  split-up and remove final step of Expansion Algorithm.
Fixes #175 and fixes #183.
cc/ @kasie
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/184.html" title="Last updated on Oct 31, 2019, 10:10 PM UTC (2dc02c1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/184/2f36a51...2dc02c1.html" title="Last updated on Oct 31, 2019, 10:10 PM UTC (2dc02c1)">Diff</a>
> Clarify that expansion steps looking for entries

- index.html
Fixes #188.
cc/ @kasei
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/190.html" title="Last updated on Oct 31, 2019, 11:39 PM UTC (f457ed6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/190/da9b2f0...f457ed6.html" title="Last updated on Oct 31, 2019, 11:39 PM UTC (f457ed6)">Diff</a>
> For warnings, change to "return" rather than "abort".

- index.html
Now it is always represented as an array in a term definition.
Fixes #181.
cc/ @kasei
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/186.html" title="Last updated on Oct 31, 2019, 11:39 PM UTC (62d07f1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/186/d930363...62d07f1.html" title="Last updated on Oct 31, 2019, 11:39 PM UTC (62d07f1)">Diff</a>
> Clarifications on _container mapping_

- index.html
* _included result_ => _expanded value_.
* Cleanup variable usage, particularly for parameters. When invoking an algorithm, a variable syntax is used to refer to the parameter, even though this confuses scope.
WebIDL has a better way of defining parameters and scope, but this is only used for API entrypoints and data-structures. A more comprehensive, but substantially more involved solution would be to define all algorithms as WebIDL methods, and local data-structures using WebIDL so that reference scopes were entirely clear.
Fixes #192 and fixes #193.
cc/ @kasei
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/194.html" title="Last updated on Nov 2, 2019, 9:16 PM UTC (c8eb1e1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/194/dd3fdfd...c8 …
> Variable confusion

- index.html
* Clarify dangling "otherwise" in 13.8.3.1. Fixes #197.
* Clarify expansion step involving `@id` and _expanded index_. Fixes #198.
* Clarify some context processing steps. Fixes #199.
cc/ @kasei
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Nov 4, 2019, 11:25 PM UTC)_.
<details>
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fjson-ld-api%2Fc6568babe1495cb20b6650b86d456ee7a818e345%2Findex.html%3FisPreview%3Dt …
> Kasei clarifications

- index.html
- tests/expand-manifest.html
- tests/expand-manifest.jsonld
- tests/expand/0117-in.jsonld
- tests/expand/0117-out.jsonld
- tests/expand/0118-in.jsonld
- tests/expand/0118-out.jsonld
- tests/expand/e050-in.jsonld
- tests/toRdf-manifest.html
- tests/toRdf-manifest.jsonld
- tests/toRdf/e117-in.jsonld
- tests/toRdf/e117-out.nq
- tests/toRdf/e118-in.jsonld
- tests/toRdf/e118-out.nq
- tests/toRdf/ee50-in.jsonld
* Allow terms starting with a colon to not be treated as IRIs. For #189
* Add "document relative" when expanding values of `@reverse` in term creation.
Remove the check for IRI or blank node after calling IRI expansion, as if it were a native value, it would have been detected, and otherwise, strings will be percent-encoded to create IRIs.
For #195.
cc/ @azaroth42 @kasei @lo48576
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/203.html" title="Last updated on Nov 7, 2019, 9:23 PM UTC (356e4f4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/203/0d787f2...356e4f4.html" title="Last updated on Nov 7, 2019, 9:23 PM UTC (356e4f4)">Diff</a>
> Terms with colon

- index.html
- tests/expand-manifest.html
- tests/expand-manifest.jsonld
- tests/expand/0119-in.jsonld
- tests/expand/0119-out.jsonld
- tests/expand/0120-in.jsonld
- tests/expand/0120-out.jsonld
- tests/expand/0121-in.jsonld
- tests/expand/0121-out.jsonld
- tests/expand/0122-in.jsonld
- tests/expand/0122-out.jsonld
- tests/toRdf-manifest.html
- tests/toRdf-manifest.jsonld
- tests/toRdf/e119-in.jsonld
- tests/toRdf/e119-out.nq
- tests/toRdf/e120-in.jsonld
- tests/toRdf/e120-out.nq
- tests/toRdf/e121-in.jsonld
- tests/toRdf/e121-out.nq
- tests/toRdf/e122-in.jsonld
- tests/toRdf/e122-out.nq
Add text with ABNF for recognizing, warning and ignoring keyword-like strings and add expansion and toRdf tests.
For #191 
Still requires changes to syntax.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/204.html" title="Last updated on Nov 8, 2019, 11:02 PM UTC (3b18c05)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/204/d98d011...3b18c05.html" title="Last updated on Nov 8, 2019, 11:02 PM UTC (3b18c05)">Diff</a>
> Keyword space

- index.html
- tests/expand-manifest.jsonld
* Type entries in a term definition and describe the properties of the active context.
* Add note to step on error handling for `@propagate`.
* Change _value_ to _context_ in context processing, and clarify that the base IRI used for resolving relative IRIs is that of the document containing the _local context_.
* Describe and use **invalid `@protected` value**.
* Be more explicit about parameters passed to IRI expansion.
Fixes #206.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/208.html" title="Last updated on Nov 11, 2019, 11:58 PM UTC (45f27b5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/208/c6147ce...45f27b5.html" title="Last updated on Nov 11, 2019, 11:58 PM UTC (45f27b5)">Diff</a>
> Algorithm clarifications

- index.html
* Remove pointless step in expansion algorithm. Fixes #213.
* Add missing hyphen to "property-scoped context" variable in expansion algorithm. Fixes #214. 
* Clarify when input does not have `@type` when setting "input type" variable. Fixes #215.
cc/ @kasei
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/217.html" title="Last updated on Nov 20, 2019, 10:08 PM UTC (a3a664e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/217/0090f01...a3a664e.html" title="Last updated on Nov 20, 2019, 10:08 PM UTC (a3a664e)">Diff</a>
> Kasei updates

- index.html
and add a clause allowing implementations to vary as appropriate for their native environments.
For #212.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/221.html" title="Last updated on Nov 21, 2019, 10:12 PM UTC (5ff68ef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/221/4c3ea8b...5ff68ef.html" title="Last updated on Nov 21, 2019, 10:12 PM UTC (5ff68ef)">Diff</a>
> Use "deferred" instead of "asynchronous" in API section

- index.html
Also describes considerations for implementations to compare values.
For w3c/json-ld-syntax#296.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/218.html" title="Last updated on Nov 22, 2019, 7:13 PM UTC (d5c404b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/218/5622471...d5c404b.html" title="Last updated on Nov 22, 2019, 7:13 PM UTC (d5c404b)">Diff</a>
> Add note on `@version` being `1.1` not being semantic versioning.

- index.html
As a fix for https://github.com/w3c/respec/issues/2582
Also, removed `issueBase`, as it's is automatically generated from `github` configuration option.
***
<a href="https://pr-preview.s3.amazonaws.com/sidvishnoi/json-ld-api/pull/229.html" title="Last updated on Nov 25, 2019, 11:35 AM UTC (fcf57b3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/229/44bb9c0...sidvishnoi:fcf57b3.html" title="Last updated on Nov 25, 2019, 11:35 AM UTC (fcf57b3)">Diff</a>
> chore: fix link to commits being wrong

- common/terms.html
- index.html
Link "form of an IRI" to ABNF for an IRI.
Fixes #222.
cc/ @kasei.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/224.html" title="Last updated on Nov 22, 2019, 9:52 PM UTC (ef8ceb3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/224/a2f7bdd...ef8ceb3.html" title="Last updated on Nov 22, 2019, 9:52 PM UTC (ef8ceb3)">Diff</a>
> Update section reference for IRI.

- index.html
This came up for me when working on JSON literal support in jsonld-java: https://github.com/jsonld-java/jsonld-java/pull/265/commits/f990f28e597a0ec6677b1525f99dff45c0861cc7.
13.3. in https://w3c.github.io/json-ld-api/#algorithm-0 specifies `invalid type mapping` for `@json` with processing mode 1.0. In 13.4. it says _otherwise_ (which includes `@json` with 1.1) yield `invalid type mapping`, unless type is  `@id` or `@vocab`. This results in `invalid type mapping` for `@json` here. That is not intended, is it?
See also https://github.com/digitalbazaar/jsonld.js/blob/6cbb389c41d3c589907ce0da4fc1127349aad830/lib/context.js#L503, which has a different structure, but seems to make sure the error is not thrown for `@json`.
***
<a href="https://pr-preview.s3.amazonaws.com/fsteeg/json-ld-api/pull …
> Add missing mention of `@json` in create term definitions

- tests/manifest.html
- tests/template.haml
> Fix typos in tests/manifest.html and template.haml

- index.html
and errant use in a call to IRI Compaction.
Fixes #233.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/236.html" title="Last updated on Dec 6, 2019, 11:34 PM UTC (c2fb0ab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/236/a1060cd...c2fb0ab.html" title="Last updated on Dec 6, 2019, 11:34 PM UTC (c2fb0ab)">Diff</a>
> Remove unused _propagate_ argument to Create Term Definition

- tests/expand-manifest.jsonld
- tests/expand/js13-in.jsonld
- tests/expand/js13-out.jsonld
- tests/expand/js14-in.jsonld
- tests/expand/js14-out.jsonld
Tests for an implementation issue found in jsonld.js:
https://github.com/digitalbazaar/jsonld.js/pull/346
> Add JSON literal alias tests.

- tests/toRdf-manifest.html
- tests/toRdf-manifest.jsonld
- tests/toRdf/js16-in.jsonld
- tests/toRdf/js16-out.nq
- tests/toRdf/js17-in.jsonld
- tests/toRdf/js17-out.nq
This goes along with https://github.com/w3c/json-ld-api/pull/238.
Note that the added `js#` ids do not line up with expand tests due to some extra tests in the toRdf namespace.  We might need to realign and/or sync them to avoid confusion.
> Add toRdf JSON literal alias tests.

- index.html
For #245.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/251.html" title="Last updated on Dec 18, 2019, 10:13 PM UTC (10a858b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/251/3838d3c...10a858b.html" title="Last updated on Dec 18, 2019, 10:13 PM UTC (10a858b)">Diff</a>
> Update Create Term Definition to set defined[term] to true in 16.5.

- index.html
- tests/README.md
- tests/compact-manifest.html
- tests/expand-manifest.html
- tests/flatten-manifest.html
- tests/fromRdf-manifest.html
- tests/html-manifest.html
- tests/html-manifest.jsonld
- tests/manifest.html
- tests/remote-doc-manifest.html
- tests/template.haml
- tests/toRdf-manifest.html
- tests/vocab.html
- tests/vocab.jsonld
- tests/vocab_template.haml
* It MAY be added on requests, and MUST be handled in responses.
* Add xhtml version of html/e001.
* Update test vocabulary, README, and manifest descriptions to describe default content types for test case properties identifying files, and how the _contentType_ option will override that for the _input_property.
For #244.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/250.html" title="Last updated on Dec 19, 2019, 9:18 PM UTC (b8df302)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/250/4b33c52...b8df302.html" title="Last updated on Dec 19, 2019, 9:18 PM UTC (b8df302)">Diff</a>
> Add text on handling application/xhtml+xml.

- index.html
For #246.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/252.html" title="Last updated on Dec 19, 2019, 9:36 PM UTC (b5b7c08)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/252/7a498f5...b5b7c08.html" title="Last updated on Dec 19, 2019, 9:36 PM UTC (b5b7c08)">Diff</a>
> Pass `false` for _propagate_ when expanding and adding a type-scoped context

- tests/expand-manifest.html
- tests/expand-manifest.jsonld
- tests/expand/js21-in.jsonld
- tests/expand/js21-out.jsonld
- tests/toRdf-manifest.html
- tests/toRdf-manifest.jsonld
- tests/toRdf/js21-in.jsonld
- tests/toRdf/js21-out.nq
Tests that no processing is done on a `@context`.
This is a test for https://github.com/w3c/json-ld-api/issues/237.
> Add test for JSON literal with a context.

- index.html
Building on @gkellogg's PR #247 to address issue #241, I made a further change that's hopefuly not too disruptive, and should address @kasei's [comment](https://github.com/w3c/json-ld-api/pull/247#issuecomment-567258296).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/266.html" title="Last updated on Dec 20, 2019, 11:26 PM UTC (1bb3603)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/266/0319468...1bb3603.html" title="Last updated on Dec 20, 2019, 11:26 PM UTC (1bb3603)">Diff</a>
> Improve fix to #241

- index.html
addresses #261
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/267.html" title="Last updated on Dec 20, 2019, 11:38 PM UTC (af16ed0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/267/6aa573b...af16ed0.html" title="Last updated on Dec 20, 2019, 11:38 PM UTC (af16ed0)">Diff</a>
> added missing keywords in step 28 (Create Term Definition)

- index.html
For #241.
@davidlehn and @kasei, I change the inline note to a block note, but I don't think it improves it. Please suggest any other changes you think would improve both formatting and clarity.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/273.html" title="Last updated on Dec 23, 2019, 8:09 PM UTC (12c9e21)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/273/3e9626a...12c9e21.html" title="Last updated on Dec 23, 2019, 8:09 PM UTC (12c9e21)">Diff</a>
> Change inline note to block note in Create Term Definition step 16.

- index.html
For #262.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/272.html" title="Last updated on Dec 24, 2019, 6:48 PM UTC (95b5873)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/272/f33a219...95b5873.html" title="Last updated on Dec 24, 2019, 6:48 PM UTC (95b5873)">Diff</a>
> Move expansion step 13.15 to out of the loop to step 14.

- index.html
For #269.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/275.html" title="Last updated on Dec 24, 2019, 7:04 PM UTC (272fab3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/275/f33a219...272fab3.html" title="Last updated on Dec 24, 2019, 7:04 PM UTC (272fab3)">Diff</a>
> Update expansion to expand _input type_ before comparing with `@type`.

- index.html
* Changed step 1.3.2.5.1 to be a note on the following step, as it was non-procedural. For #278.
* Changed step 1.3.2.5.2 to use the add method, rather than use "append". For #279.
* Changed step 1.2 to initialize <var>triple</var>, not <var>graph</var>, which is an input. For #281.
* Added a new step 13.1 to Object to RDF conversion to create a variable for `@language`. For #277.
* Updated step 6 of Object to RDF to only check that a datatype is well-formed if it is not null, and to specify that the check is for a well-formed IRI. For #282.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/286.html" title="Last updated on Dec 26, 2019, 9:23 PM UTC (a4254e2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/286/188dea7...a4254e2.html" …
> To RDF improvements

- index.html
not set <var>result</var> to `null`.
For #284.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/287.html" title="Last updated on Dec 26, 2019, 9:35 PM UTC (9c9612f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/287/6cf9ecb...9c9612f.html" title="Last updated on Dec 26, 2019, 9:35 PM UTC (9c9612f)">Diff</a>
> Changed step 18 of the Expansion algorithm to return `null`

- tests/expand-manifest.html
- tests/expand-manifest.jsonld
- tests/expand/0122-out.jsonld
- tests/expand/js22-in.jsonld
- tests/expand/js22-out.jsonld
- tests/expand/js23-in.jsonld
- tests/expand/js23-out.jsonld
- tests/toRdf-manifest.html
- tests/toRdf-manifest.jsonld
- tests/toRdf/js22-in.jsonld
- tests/toRdf/js22-out.nq
- tests/toRdf/js23-in.jsonld
- tests/toRdf/js23-out.nq
Note that this identifies an issue with the expected result for expand/0122, which was inconsistent with the spec.
For #270.
> Adds tests for null json literals, and fixes one expected result

- index.html
Move step 5.2.5 to 5.2.4.1.
For #265.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/289.html" title="Last updated on Dec 27, 2019, 7:50 PM UTC (4003c43)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/289/2d6fe87...4003c43.html" title="Last updated on Dec 27, 2019, 7:50 PM UTC (4003c43)">Diff</a>
> Add some notes to Context Processing algorithm for strings.

- index.html
For #276.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/285.html" title="Last updated on Dec 27, 2019, 7:07 PM UTC (10100e8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/285/2d6fe87...10100e8.html" title="Last updated on Dec 27, 2019, 7:07 PM UTC (10100e8)">Diff</a>
> Improve step 3 of the node map generation algorithm.

- index.html
to restore step 16.1, and move 16.2-16.n to a new 16.2 "Otherwise" substep.
For #241.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/288.html" title="Last updated on Dec 31, 2019, 6:38 PM UTC (0f3bd0b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/288/2d6fe87...0f3bd0b.html" title="Last updated on Dec 31, 2019, 6:38 PM UTC (0f3bd0b)">Diff</a>
> Rework Create Term Definition step 16 (again)

- index.html
For #298.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/300.html" title="Last updated on Jan 3, 2020, 7:13 PM UTC (cacb19f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/300/3594011...cacb19f.html" title="Last updated on Jan 3, 2020, 7:13 PM UTC (cacb19f)">Diff</a>
> Allow datatype to be `@json` or a well-formed IRI in Object to RDF.

- index.html
which were formally in a paragraph following the algorithm steps, into the `expand()` API method to be performed after the algorithm has completed.
This restores previous desired behavior that the expansion algorithm typically results in a map when starting with a map, and not an array containing that map.
For #294.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/299.html" title="Last updated on Jan 3, 2020, 7:51 PM UTC (41f4c8a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/299/3594011...41f4c8a.html" title="Last updated on Jan 3, 2020, 7:51 PM UTC (41f4c8a)">Diff</a>
> Move last 3 steps of the expansion algorithm

- index.html
for expanding with a property-scoped context.
For #301.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/302.html" title="Last updated on Jan 3, 2020, 9:35 PM UTC (9bb5ddc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/302/8dc2721...9bb5ddc.html" title="Last updated on Jan 3, 2020, 9:35 PM UTC (9bb5ddc)">Diff</a>
> Add missing _override proected_ option

- index.html
not _active context_, which is updated along the way.
For issue #304.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/307.html" title="Last updated on Jan 8, 2020, 12:41 AM UTC (367b0d2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/307/f61b497...367b0d2.html" title="Last updated on Jan 8, 2020, 12:41 AM UTC (367b0d2)">Diff</a>
> Look for local contexts for `@type` using the _type-scoped context_

- index.html
- tests/expand-manifest.html
- tests/expand-manifest.jsonld
in Expansion Algorithm step 14.
For #295.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/297.html" title="Last updated on Jan 3, 2020, 12:19 AM UTC (6ba6d40)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/297/3594011...6ba6d40.html" title="Last updated on Jan 3, 2020, 12:19 AM UTC (6ba6d40)">Diff</a>
> Optionally order when iterating on _nesting-key_

- index.html
* Updated the language in step 8 of the Value Compaction Algorithm to be consistent with other steps. For #313.
* Fix some references that had a line-wrap affecting the text styling. Fixes #315.
* Update language from Compaction to use _inside reverse_ **for the _reverse_ flag**. Fixes #316.
* Add clarity when adding an array to an array using concatenate. For #323.
* Clarify where compacted key/value is added in steps 12.8.7.4.2 and 12.8.7.4.3. For #324.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/325.html" title="Last updated on Jan 15, 2020, 11:33 PM UTC (67cb0e2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/325/fc9e30f...67cb0e2.html" title="Last updated on Jan 15, 2020, 11:33 PM UTC (67cb0e2)">Diff</a>
> Variable names

- index.html
even if it is already a _graph object_.
Fixes #311.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/335.html" title="Last updated on Jan 17, 2020, 11:01 PM UTC (aaa7c88)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/335/4a41d9c...aaa7c88.html" title="Last updated on Jan 17, 2020, 11:01 PM UTC (aaa7c88)">Diff</a>
> Update 13.21.1 to _always_ make _ev_ a graph object

- index.html
to always use array semenatics
Fixes #322.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/338.html" title="Last updated on Jan 18, 2020, 8:02 PM UTC (6971f4f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/338/ea69ec2...6971f4f.html" title="Last updated on Jan 18, 2020, 8:02 PM UTC (6971f4f)">Diff</a>
> Clean up language in the compaction algorithm for _container_

- index.html
rather than the algorithm, into the description of `compact()` in the API.
For #318.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/336.html" title="Last updated on Jan 18, 2020, 7:57 PM UTC (218b9cf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/336/95f5d46...218b9cf.html" title="Last updated on Jan 18, 2020, 7:57 PM UTC (218b9cf)">Diff</a>
> Move parts of Compaction Algorithm that relate to the API call

- index.html
in the Compaction algorithm.
Fixes #334.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/341.html" title="Last updated on Jan 21, 2020, 9:53 PM UTC (e6f944f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/341/b4c20a4...e6f944f.html" title="Last updated on Jan 21, 2020, 9:53 PM UTC (e6f944f)">Diff</a>
> Simplify language for returning an array if there is a single value

- tests/expand-manifest.html
- tests/expand-manifest.jsonld
- tests/expand/c032-in.jsonld
- tests/toRdf-manifest.html
- tests/toRdf-manifest.jsonld
- tests/toRdf/c032-in.jsonld
> Add an embedded context which is unused, but should indicate an error.

- common/algorithm-terms.html
- index.html
This is an attempt to simplify language by extracting common steps into "macros" described as algorithm terms.
* Be more clear about what it meant by "it" in "set it" in various parts of the text. Fixes #330.
* Added "add value" macro to algorithm terms to manage adding values entries in objects and properly deal with array conversion.
* Added _iri compacting_ macro and use where more verbose IRI Compaction language was used.
* Added _iri expanding_ macro and use where more verbose IRI Expansion language was used.
* Rewrite many entries in Compaction and elsewhere to use "add value" to simplify language.
For #327, #329, #330, and #332.
cc/ @kasei
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/339.html" title="Last updated on Jan 21, 2020, 9:56 PM UTC …
> Reduce boilerplate language by introducing macros.

- index.html
Fixes #342.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/344.html" title="Last updated on Jan 21, 2020, 10:08 PM UTC (82f27a6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/344/8d2c4f8...82f27a6.html" title="Last updated on Jan 21, 2020, 10:08 PM UTC (82f27a6)">Diff</a>
> Move step 3.14 in Inverse Context algorithm up to be 3.13.6.

- tests/expand-manifest.html
- tests/expand-manifest.jsonld
- tests/expand/so12-in.jsonld
- tests/expand/so13-context.jsonld
- tests/expand/so13-in.jsonld
- tests/toRdf-manifest.html
- tests/toRdf-manifest.jsonld
- tests/toRdf/so12-in.jsonld
- tests/toRdf/so13-context.jsonld
- tests/toRdf/so13-in.jsonld
- Looks like an oversight that test error codes don't match the spec. This fix will break any implementations running against those tests.
- Synced the expand/toRdf `@import` tests and use 1.0 mode for the 1.0 tests.
> Fix "invalid context entry" codes and improve `@import` tests.

- common/jsonld.js
- index.html
to Expansion, Context Processing and Create Term definition.
The change touches a lot of parts, and leaves a little hand waiving when a context has been previously loaded.
For #265.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/356.html" title="Last updated on Jan 29, 2020, 7:43 PM UTC (2614999)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/356/2f57a54...2614999.html" title="Last updated on Jan 29, 2020, 7:43 PM UTC (2614999)">Diff</a>
> Updates to pass base URL

- Gemfile.lock
- index.html
when creating i18n datatype or compound literal.
For #337.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/363.html" title="Last updated on Jan 28, 2020, 11:47 PM UTC (7771d14)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/363/2f57a54...7771d14.html" title="Last updated on Jan 28, 2020, 11:47 PM UTC (7771d14)">Diff</a>
> Normalize language tags to lower case

- index.html
and remove most conditional use or initialization of those options.
Fixes #358.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/362.html" title="Last updated on Jan 29, 2020, 11:41 PM UTC (a9c7c7b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/362/c25e18c...a9c7c7b.html" title="Last updated on Jan 29, 2020, 11:41 PM UTC (a9c7c7b)">Diff</a>
> Clarify that API options use default values from JsonLdOptions

- common/jsonld.js
- index.html
for the conversion of the JSON Literals in the round tripping section.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/366.html" title="Last updated on Jan 29, 2020, 7:17 PM UTC (81375d9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/366/c6f437a...81375d9.html" title="Last updated on Jan 29, 2020, 7:17 PM UTC (81375d9)">Diff</a>
> Reference the rdf:JSON datatype of the syntax document

- index.html
- tests/README.md
- tests/context.jsonld
- tests/expand-manifest.html
- tests/expand-manifest.jsonld
- tests/html-manifest.html
- tests/manifest.html
- tests/remote-doc-manifest.html
- tests/template.haml
- tests/toRdf-manifest.jsonld
* Make _expandContext_ `@type: @id` and set option values to be relative to the manifest location. Fixes #369.
* Set a fallback in `expand()` processing if there is no `documentUrl`. This uses `JsonLdOptions/base`, which could be null, or something else appropriate for when the `input` or `expandContext` is not a URL. For #370.
* Describe that if `documentUrl` is not available, values come from `JsonLdOptions/base`, which now defaults to `null`. Fixes #375.
* Reorder clauses in 5.1.2 to make it more clear that setting _base IRI_ and _original base URL_ of the new _active context_ is unconditional, unlinke _previous_context_.
* Create values for _context document_ and _loaded context_ in the case that the previous document was cached in 5.2.3 of the Create Context Algorithm. Fixes #372.
* …
> More context processing

- tests/expand-manifest.html
- tests/expand-manifest.jsonld
- tests/expand/pr38-out.jsonld
- tests/expand/pr39-in.jsonld
- tests/expand/pr39-out.jsonld
- tests/toRdf-manifest.html
- tests/toRdf-manifest.jsonld
- tests/toRdf/pr38-out.nq
- tests/toRdf/pr39-in.jsonld
- tests/toRdf/pr39-out.nq
as the keyword-like value of `@reverse` is ignored, and does not generate an error.
Fixes #386.
> Update expand/pr39 and toRdf/pr39 to make them positive tests

- common/algorithm-terms.html
- common/terms.html
- index.html
Fixes #383.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/384.html" title="Last updated on Feb 27, 2020, 6:13 PM UTC (d3966e9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/384/ad97b98...d3966e9.html" title="Last updated on Feb 27, 2020, 6:13 PM UTC (d3966e9)">Diff</a>
> WebIDL cleanup

- tests/html-manifest.html
- tests/html-manifest.jsonld
e011, e012, e013, r011, r012, and r013 from "invalid script element" to "load document failed",
Fixes #399.
> Update test expectations for HTML tests

- index.html
to add values to <var>nest result</var> instead of <var>result</var> as was originally intended.
Fixes #403.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 6, 2020, 12:14 AM UTC)_.
<details>
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fjson-ld-api%2Fe524070b17016ae36154307ae5ebd7abbbf46ec2%2Findex.html%3FisPreview%3Dtrue)
```
Navigation timeout of 30000 ms exceeded
```
_If you don't have enough …
> Update step 12.8.1 of the Compaction Algorithm

- tests/expand-manifest.html
- tests/expand-manifest.jsonld
- tests/expand/c034-context.jsonld
- tests/expand/c034-in.jsonld
- tests/expand/c034-out.jsonld
- tests/toRdf-manifest.html
- tests/toRdf-manifest.jsonld
- tests/toRdf/c034-context.jsonld
- tests/toRdf/c034-in.jsonld
- tests/toRdf/c034-out.nq
We didn't have any tests where a scoped context was a URL, which affects implementations which preload remote contexts.
> Add expansion test where scoped context is a URL.

- index.html
to exclude `@type` from copied values, leaving it to 2.2.2.
Fixes #407.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 10, 2020, 8:53 PM UTC)_.
<details>
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fjson-ld-api%2F680cee3367541e8576c2798133a94852995add39%2Findex.html%3FisPreview%3Dtrue)
```
Navigation timeout of 30000 ms exceeded
```
_If you don't have enough information above to solve the error by …
> Update step 2.2.1 of Merge Node Maps

- index.html
by compacting _index key_ in step 12.8.9.6.
Fixes #406.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 10, 2020, 9:50 PM UTC)_.
<details>
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fjson-ld-api%2F680cee3367541e8576c2798133a94852995add39%2Findex.html%3FisPreview%3Dtrue)
```
Navigation timeout of 30000 ms exceeded
```
_If you don't have enough information above to solve the error by yourself (or to …
> Update Compaction algorithm to re-initialize _container key_

- index.html
Sort the descriptions to match the ordered enum list above.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 15, 2020, 7:58 PM UTC)_.
<details>
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fjson-ld-api%2F811419fba0804f24d66d9b4f59dd3bc6c0f1e065%2Findex.html%3FisPreview%3Dtrue)
```
Navigation timeout of 30000 ms exceeded
```
_If you don't have enough information above to solve the error by yourself (or to …
> Order JsonLdErrorCode descriptions.

- index.html
by moving the preceding step to 3.9.
Fixes #415.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/423.html" title="Last updated on Mar 17, 2020, 7:59 PM UTC (0dfb791)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/423/9104fcb...0dfb791.html" title="Last updated on Mar 17, 2020, 7:59 PM UTC (0dfb791)">Diff</a>
> Clarified step 3.13 in the Inverse Context Creation algorithm

- index.html
in the description of _invalid container mapping_.
Fixes #424.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/427.html" title="Last updated on Mar 21, 2020, 6:04 PM UTC (66f0f60)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/427/0fdafb0...66f0f60.html" title="Last updated on Mar 21, 2020, 6:04 PM UTC (66f0f60)">Diff</a>
> Added missing values for `@container` 

- tests/expand-manifest.jsonld
- tests/expand/c035-in.jsonld
- tests/expand/c035-out.jsonld
- tests/toRdf-manifest.jsonld
- tests/toRdf/c035-in.jsonld
- tests/toRdf/c035-out.nq
As discussed in #408, this adds a dedicated toRdf test for checking that terms should make use of @vocab relative to the scope in which the term was defined.
> Add term scoping test for toRdf

- index.html
Add a keyword section and describe `@preserve`.
Fixes w3c/json-ld-syntax#332.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/426.html" title="Last updated on Mar 21, 2020, 5:55 PM UTC (fa836ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/426/0fdafb0...fa836ae.html" title="Last updated on Mar 21, 2020, 5:55 PM UTC (fa836ae)">Diff</a>
> Describe @preserve

- tests/expand-manifest.html
- tests/expand-manifest.jsonld
- tests/expand/0129-in.jsonld
- tests/expand/0129-out.jsonld
- tests/expand/0130-in.jsonld
- tests/expand/0130-out.jsonld
- tests/toRdf-manifest.html
- tests/toRdf-manifest.jsonld
- tests/toRdf/e129-in.jsonld
- tests/toRdf/e129-out.nq
- tests/toRdf/e130-in.jsonld
- tests/toRdf/e130-out.nq
This came up when fixing https://github.com/jsonld-java/jsonld-java/issues/279 in https://github.com/jsonld-java/jsonld-java/pull/280, where we noticed the original issue described on [the Apache Jena list](https://lists.apache.org/thread.html/r343f27b3390dfbfd7ce9dcee4576bc532705b39d26923dfb0baf5322%40%3Cusers.jena.apache.org%3E) was not covered by the spec tests.
Relative resolution in RFC 3986 [1][2] (see `8)` in spec [3]):
- `rel` relative to `example` is `example/rel`
- `rel` relative to `example/base` is also `example/rel`
Already tested elsewhere, for clarity here, with trailing slash:
- `rel` relative to `example/base/` is `example/base/rel`
[1] https://tools.ietf.org/html/rfc3986#section-5.2
[2] https://blog.cdivilly.com/2019/02/28/uri-trailing-slashes
[3] …
> Verify URI resolution relative to base without trailing slash

- reports/index.html
- reports/jsonld-streaming-parser-earl.ttl
- reports/rdf-parse.ttl
* jsonld-streaming-parser passes all toRdf tests.
* rdf-parse passes all (toRdf) HTML tests.
> Add final reports of jsonld-streaming-parser and rdf-parse

- tests/README.md
- tests/compact-manifest.html
- tests/expand-manifest.html
- tests/flatten-manifest.html
- tests/html-manifest.html
- tests/manifest.html
- tests/remote-doc-manifest.html
- tests/template.haml
New version of #433.
I intentionally left the links to the JSON-LD manifests in the README, instead of pointing those to their HTML counterpart.
> Fix links to/from HTML manifests

- reports/index.html
- reports/jsonld-gold-earl.ttl
Currently shows FAIL for all HTML tests, could probably use `earl:untested` or `earl:inapplicable` for things not specifically intended to pass.
cc/ @ kazarena
> Json gold EARL report

- reports/pyld-earl.ttl
- Renamed report since it's easier to create api+framing reports now.
- I generated output index.html and it looks ok, I think.  Lots of data, hard to check it all by sight.
- My tools had odd parsing errors rebuilding manifest.nt, I'm not sure how that effects things.
- Generating earl.jsonld and index.html caused huge diff bloat due to non-deterministic ordering.  So I left them out of this PR for now. Do the tools allow output property sorting to avoid that?  I'm not sure about the jsonld part, but perhaps the html template itself could do some of that?
- What time resolution is needed for these tests? I dropped the subsecond part for PyLD tests.  Seems like just the day would be enough for this purpose.  That could help a bit with any daily report update diff churn and make files a …
> Update PyLD test report for 2.0.0.

- tests/context.jsonld
Fixes https://github.com/w3c/json-ld-api/issues/467.
> Fix trailing comma syntax error.

- reports/jsonld-js-earl.ttl
- Add report for jsonld.js 3.1.0.
- Unsure about naming convention.  Is "jsonld-js-earl.ttl" ok?
- This is missing the html support.  Still slowly trying to address that, but wanted to get in results for the rest.
> Add jsonld.js 3.1.0 test report.

- reports/index.html
- reports/template.haml
* Remove Test Definition's appendix, which was missing.
* Use stable identifiers for subject references within implementation report.
Fixes #469.
> Implementation Report fixes

- errata/errata.css
- errata/index.html
The file will be served from 
https://w3c.github.io/json-ld-api/errata/
(although we may want to set up redirections from W3C, to be discussed...)
See: https://raw.githack.com/w3c/json-ld-api/add-errata/errata/index.html for now.
If this is fine, the same file will be added to the syntax and framing specs (maybe to streaming?), with obvious copy-paste actions.
> Added the errata management file

- index.html
- publication-snapshots/PR/Overview.html
Added the superseding remark to SOTD
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/486.html" title="Last updated on May 6, 2020, 7:30 PM UTC (b78153f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/486/462ad7c...b78153f.html" title="Last updated on May 6, 2020, 7:30 PM UTC (b78153f)">Diff</a>
> supersede remark

- reports/README.md
- reports/index.html
- reports/rust-sophia-earl.ttl
I could not update the reports;
the command `rake report/manifests.nt` yields the following error:
>  The git source https://github.com/ruby-rdf/json-ld.git is not yet checked out. Please run `bundle install` before trying to start your application
even though I *did* run bundle install (with success).
> fix version number in sophia report

- reports/java-jsonp-ld-earl.ttl
Please add the test report. JSONP-LD is an open source implementation in Java aiming to fully support the specification. Version 0.2.2. supports expansion and compaction. Thank you.
https://github.com/filip26/jsonp-ld
> add JSONP-LD 0.2.2 EARL

- index.html
For w3c/json-ld-wg#150.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/493.html" title="Last updated on Jun 8, 2020, 12:43 AM UTC (f64d727)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/493/691ca67...f64d727.html" title="Last updated on Jun 8, 2020, 12:43 AM UTC (f64d727)">Diff</a>
> Remove atrisk notes.

- index.html
This silences ReSpec, and is probably better than just removing [Exposed] altogether.
Thanks to @hober for the advice.
If acceptable, a similar change will be required for JSON-LD Framing.
CC/ @swickr @iherman
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/500.html" title="Last updated on Jun 26, 2020, 6:57 PM UTC (95a5df8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/500/e4e8dc5...95a5df8.html" title="Last updated on Jun 26, 2020, 6:57 PM UTC (95a5df8)">Diff</a>
> Make a global JsonLd interface.

- common/jsonld.js
- index.html
Note that we discuss changing our canonicalization requirements to JCS when it becomes available, which it is now. Perhaps something to take up post-publication.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/501.html" title="Last updated on Jun 30, 2020, 10:25 PM UTC (c22aaa5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/501/a150a99...c22aaa5.html" title="Last updated on Jun 30, 2020, 10:25 PM UTC (c22aaa5)">Diff</a>
> Change JCS bibref to RFC8785, as it's now published.

- tests/toRdf-manifest.html
- tests/toRdf-manifest.jsonld
The `toRdf` tests manifest contains multiple entries for ids `#t0124` and `#t012t`. I rename them to `#te124` and `#te125` as that looks like how they are supposed to fit in with the sequence of other tests.
I checked the other test manifests and did not find any other deduplicate ids. Helper script: [dedup.js](https://github.com/w3c/json-ld-api/files/5711467/dedup.js.txt)
> Rename duplicate ids in toRdf manifest

- index.html
- tests/compact-manifest.html
- tests/compact-manifest.jsonld
- tests/compact/0112-context.jsonld
- tests/compact/0112-in.jsonld
- tests/compact/0112-out.jsonld
- tests/compact/0113-context.jsonld
- tests/compact/0113-in.jsonld
- tests/compact/0113-out.jsonld
The value of `@index` on a property map can be a Compact IRI in addition to an IRI. The Compaction Algorithm is updated to first expand this value before re-compacting it. Added additional language to the Compaction Algorithm step 12.8.9.6.1 to first expand container key before compacting it.
Also fixed an emergent issue with WebIDL reference for LoadDocumentCallback/url.
Adds two new compaction tests.
Fixes #514.
CC/ @vcharpenay
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/528.html" title="Last updated on May 15, 2021, 7:07 PM UTC (45036dc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/528/b7df683...45036dc.html" title="Last updated on May 15, 2021, 7:07 PM UTC (45036dc)">Diff</a>
> Fix compacting property-based indexes.

- index.html
Will prevent future misunderstandings like #567
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/json-ld-api/pull/569.html" title="Last updated on Jun 20, 2023, 9:40 PM UTC (7872438)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/569/7a665c1...TallTed:7872438.html" title="Last updated on Jun 20, 2023, 9:40 PM UTC (7872438)">Diff</a>
> Minor editorial rephrasing to clarify

- tests/expand-manifest.jsonld
- tests/expand/pr41-in.jsonld
- tests/expand/pr41-out.jsonld
- tests/toRdf-manifest.jsonld
- tests/toRdf/pr41-in.jsonld
- tests/toRdf/pr41-out.nq
- Add test of redefining equivalent protected id terms in different forms:
- `"foo": {"@id": "ex:foo"}`
- `"foo": "ex:foo"`
This currently fails in jsonld.js and with the distiller.  Should implementations be considering these forms equivalent as far as protected redefinition checks are concerned?
> Add similar id protected term redefinition test.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/575.html" title="Last updated on Aug 6, 2023, 8:12 PM UTC (104c581)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/575/a6850f2...104c581.html" title="Last updated on Aug 6, 2023, 8:12 PM UTC (104c581)">Diff</a>
> Add"lint-ignore" class to some unused definitions to silence warnings.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/578.html" title="Last updated on Sep 15, 2023, 8:01 PM UTC (dd2ca3c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/578/6bf9ef4...dd2ca3c.html" title="Last updated on Sep 15, 2023, 8:01 PM UTC (dd2ca3c)">Diff</a>
> remove surious paragraph in the description of frameExpansion

- tests/expand-manifest.jsonld
- tests/expand/pr42-in.jsonld
- tests/toRdf-manifest.jsonld
- tests/toRdf/pr42-in.jsonld
- Add expand and toRdf tests to check protection flag is retained when a term is redefined the same as a protected term, and then redefined as something else, triggering a failure.
- See 4.1.11 https://www.w3.org/TR/json-ld11/#protected-term-definitions about similar overrides that don't change semantics of the protected term.
- See 4.2.2.27.2 https://www.w3.org/TR/json-ld-api/#algorithm-0 about retaining the value of protected flag.
> Test protected flag retained during redefinition.

- tests/expand-manifest.jsonld
- tests/expand/er56-in.jsonld
- tests/toRdf-manifest.jsonld
- tests/toRdf/er56-in.jsonld
See https://github.com/w3c/json-ld-api/issues/590.
- Please double check this is the correct error code.
- The test naming is still confusing, I think erNN is ok?
> Add test for `@context` redefinition.

- .github/workflows/generate.yml
- Gemfile.lock
- tests/expand-manifest.html
- tests/toRdf-manifest.html
> Automatically build HTML versions of test manifests.

- tests/expand-manifest.html
- tests/expand-manifest.jsonld
- tests/expand/pr43-in.jsonld
- tests/expand/pr43-out.jsonld
- tests/toRdf-manifest.html
- tests/toRdf-manifest.jsonld
- tests/toRdf/pr43-in.jsonld
- tests/toRdf/pr43-out.nq
Adds a test for a protected `@graph` `@container` property that nullifies it's `@context`.  This is similar to a pattern found in the VC Data Model 2.0 context.  There are other test variations of context nullification, graph properties, and protection rules, etc, but there doesn't seem to be one with this combination.  jsonld.js was failing this test but other implementations pass.
Are other variations of this test needed?  It looks like most base features are covered, but perhaps tricky combinations of features might expose edge case issues.  Help needed.
See:
https://github.com/w3c/vc-data-model/issues/1373
> Add protected graph container null context test.

- index.html
Tests are already consistent with this interpretation, although it was never documented in the API properly.
Fixes #603.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/606.html" title="Last updated on Jul 12, 2024, 2:21 PM UTC (b2ece69)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/606/30aa531...b2ece69.html" title="Last updated on Jul 12, 2024, 2:21 PM UTC (b2ece69)">Diff</a>
> The default for extractAllScripts in toRdf() should be true.

- index.html
for #380/#388, #514/#528, #565/#566. and #603/#606.
Reorganizes the change log with latest changes first. Comments out some entries in the change log which are class-1 or class-2 changes.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/616.html" title="Last updated on Oct 20, 2024, 8:30 PM UTC (5a2e5a1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/616/76319ff...5a2e5a1.html" title="Last updated on Oct 20, 2024, 8:30 PM UTC (5a2e5a1)">Diff</a>
> Add candidate change and insertions relating to previously merged class-3 changes.

- tests/html-manifest.html
- tests/html-manifest.jsonld
- tests/html/f005-context.jsonld
- tests/html/f005-in.html
- tests/html/f005-out.jsonld
Add html/f005 with extractAllScripts set to true.
See #606.
For #603.
cc/@niklasl
> Fix test output for html/f004 and add html/f005

- tests/expand-manifest.jsonld
`purpose` was missing from `t0041`. Some prior discussion here: https://github.com/json-ld/json-ld.org/pull/852.
> Rename name to purpose and add name for t0041

- tests/compact-manifest.html
- tests/compact-manifest.jsonld
- tests/compact/m023-context.jsonld
- tests/compact/m023-in.jsonld
- tests/compact/m023-out.jsonld
The algorithm inspects `compacted item` to see if it has value for `container key` when `compacted item` is not a **map**.
From ruby-rdf/json-ld#62.
> Add compaction to @type map when the compacted item is not already a map.

- index.html
Closes #622.
***
<a href="https://pr-preview.s3.amazonaws.com/multimeric/json-ld-api/pull/623.html" title="Last updated on Jan 27, 2025, 10:39 PM UTC (e97881b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/623/e9a9a01...multimeric:e97881b.html" title="Last updated on Jan 27, 2025, 10:39 PM UTC (e97881b)">Diff</a>
> Fix issue 622

- .gitignore
- index.html
- tests/expand-manifest.html
- tests/fromRdf-manifest.html
- tests/fromRdf-manifest.jsonld
- tests/fromRdf/0027-in.nq
- tests/fromRdf/0027-out.jsonld
This is my second attempt to fix this issue after https://github.com/w3c/json-ld-api/pull/619.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/625.html" title="Last updated on Jan 27, 2025, 10:44 PM UTC (33a652b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/625/f004001...33a652b.html" title="Last updated on Jan 27, 2025, 10:44 PM UTC (33a652b)">Diff</a>
> (closes #555) Fall back to default logic in `useNativeTypes` mode for RDF numbers which are not JSON numbers

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/640.html" title="Last updated on Feb 28, 2025, 10:53 AM UTC (d0e3acb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/640/746ece8...d0e3acb.html" title="Last updated on Feb 28, 2025, 10:53 AM UTC (d0e3acb)">Diff</a>
> fix validation errors and warnings

- tests/fromRdf-manifest.jsonld
The `input` and `expect` are the same as in `tli02`, while `fromRdf/li03-in.nq` and `fromRdf/li03-out.jsonld` are unused. Seems like a copy-and-paste error.
> Fix fromRdf#tli03 test case definition in manifest

- tests/compact-manifest.html
- tests/compact-manifest.jsonld
- tests/fromRdf-manifest.html
and should have `specVersion: 1.1` to not interfer with 1.0 development.
Fixes #649.
> Tests t0112 and t0113 use 1.1-specific features

- common/terms.html
- index.html
I'm not entirely satisfied with the addition in common/terms.html, as it seems too detailed for the terminology section. But...
...as pointed out in the comment of #630,
the API spec references to this definition in multiple places, and many of those links are actually for instances of the internal representation, *not* for instances of the strings or maps that represent term definition in JSON.
So the alternative would be to introduce a new name for those "internal term definition" and patch all the algorithms... which seems laborious and error-prone.
@gkellogg I don't remember what's the process for synchronizing the files in common with other specs.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/638.html" title="Last updated on Jun 4, 2025, 5:02 PM UTC …
> improve 'term definition' definition

- index.html
and using the markup for candidate corrections
This PR deprecates the old PR #637 because
- the old PR did not use candidate correction markup
- the old PR accidentally removed a part of the algorithm that should stay (that's what you get for writing PRs at 1am...)
- the old PR introduced a behavior change in the edge case where default language was undefined, but default base direction was, on the assumption that the old behavior was a bug. On second thought, I'd rather keep this for a separate issue if this is really a bug (if it is, it might also affect other algorithms, e.g. compaction).
- the changes in this PR are simpler, while achieving the same result
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/639.html" title="Last updated on Jun 15, 2025, 8:22 PM UTC …
> fix #633, in a better way

- index.html
- tests/fromRdf/0027-in.nq
- tests/fromRdf/0027-out.jsonld
- **#656 Specify 0 and 1 as valid Boolean literals in RDF to Object conversion algorithm**
- **#656 Update fromRdf test 0027 to reflect 0 and 1 as valid Boolean values**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/pull/662.html" title="Last updated on Jun 20, 2025, 6:32 PM UTC (754c657)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-api/662/f32a438...754c657.html" title="Last updated on Jun 20, 2025, 6:32 PM UTC (754c657)">Diff</a>
> (closes #656) convert `"1"^^xsd:boolean` and `"0"^^xsd:boolean` to native values
